### ISSUE TITLE
Spreadsheet name length issue

### ISSUE THREAD

**Issue by ihodes** [hammerlab/vaxrank#103]
```Traceback (most recent call last):
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/vaxrank.0.3.0/bin/vaxrank", line 11, in <module>
    sys.exit(main())
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/vaxrank.0.3.0/lib/python3.5/site-packages/vaxrank/cli.py", line 299, in main
    csv_report_path=args.output_csv)
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/vaxrank.0.3.0/lib/python3.5/site-packages/vaxrank/report.py", line 475, in make_csv_report
    df.to_excel(writer, sheet_name=sheet_name, index=False)
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/vaxrank.0.3.0/lib/python3.5/site-packages/pandas/core/frame.py", line 1464, in to_excel
    startrow=startrow, startcol=startcol)
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/vaxrank.0.3.0/lib/python3.5/site-packages/pandas/io/excel.py", line 1512, in write_cells
    wks = self.book.add_worksheet(sheet_name)
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/vaxrank.0.3.0/lib/python3.5/site-packages/xlsxwriter/workbook.py", line 171, in add_worksheet
    return self._add_sheet(name, is_chartsheet=False)
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/vaxrank.0.3.0/lib/python3.5/site-packages/xlsxwriter/workbook.py", line 634, in _add_sheet
    name = self._check_sheetname(name, is_chartsheet)
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/vaxrank.0.3.0/lib/python3.5/site-packages/xlsxwriter/workbook.py", line 688, in _check_sheetname
    sheetname)
Exception: Excel worksheet name '9_RP11-830F9.6_chr16_890XXXXXXX_X_X' must be <= 31 chars.```

**Comment by iskandr** [comment]
Trim to 31 characters?

**Comment by ihodes** [comment]
Yeah we definitely need this. What should the above be named? Just truncating seems potentially problematic
