### ISSUE TITLE
ValueError: Expected 636 peptide predictions but got 0

### ISSUE THREAD

**Issue by ihodes** [hammerlab/vaxrank#122]
Any idea how this happens/what to do with this?
```
2017-03-22 01:18:18,895 - mhctools.base_commandline_predictor:269 - WARNING - No binding predictions from netMHCcons
Traceback (most recent call last):
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/vaxrank.0.4.2/bin/vaxrank", line 11, in <module>
    sys.exit(main())
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/vaxrank.0.4.2/lib/python3.6/site-packages/vaxrank/cli.py", line 285, in main
    data = ranked_variant_list_with_metadata(args)
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/vaxrank.0.4.2/lib/python3.6/site-packages/vaxrank/cli.py", line 227, in ranked_variant_list_with_metadata
    variant_sequence_assembly=args.variant_sequence_assembly)
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/vaxrank.0.4.2/lib/python3.6/site-packages/vaxrank/core_logic.py", line 191, in ranked_vaccine_peptides
    min_epitope_score=min_epitope_score)
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/vaxrank.0.4.2/lib/python3.6/site-packages/vaxrank/core_logic.py", line 164, in generate_vaccine_peptides
    min_epitope_score=min_epitope_score)
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/vaxrank.0.4.2/lib/python3.6/site-packages/vaxrank/core_logic.py", line 61, in vaccine_peptides_for_variant
    genome=variant.ensembl).values()
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/vaxrank.0.4.2/lib/python3.6/site-packages/vaxrank/epitope_prediction.py", line 168, in predict_epitopes
    {protein_fragment.gene_name: protein_fragment.amino_acids})
  File "/pgv-results/biokepi-coco-work/toolkit-coco/python-tools/envs/vaxrank.0.4.2/lib/python3.6/site-packages/mhctools/base_predictor.py", line 132, in predict_subsequences
    n_expected, len(binding_predictions)))
ValueError: Expected 636 peptide predictions but got 0
```

**Comment by julia326** [comment]
@ihodes could you post the vaxrank inputs that resulted in this? @iskandr any possibility this is related to the recent mhctools refactor?

**Comment by iskandr** [comment]
If it's the refactoring it would have to be a problem in either the representation of input peptides or parsing of netMHCcons outputs: ```WARNING - No binding predictions from netMHCcons```. 

Can you send me the VCF this comes from?

**Comment by ihodes** [comment]
Sent via another channel.

**Comment by iskandr** [comment]
@julia326 We've fixed a few different "NetMHC dropping peptides" problems so I don't actually know if I can close this issue.

**Comment by julia326** [comment]
@iskandr I think this likely falls under the set of problems we've fixed recently. I'm happy to close this and reopen if we run into it again. Thoughts?
