### ISSUE TITLE
ImportError: No module named biotypes

### ISSUE THREAD

**Issue by JPFinnigan** [hammerlab/vaxrank#26]
Does vaxrank depend on earlier versions of Pyensembl (e.g. those prior to removal of biotypes)?

Running w/:
```
jpf-mbp:~ johnfinnigan$ vaxrank \
> --vcf ~/Desktop/WD/Results/WES/Murine/B16.F10/ISMMS/VCF/MuTect/B16.F10.0810_mutect.targets.pass.vcf \
> --bam ~/Desktop/WD/Results/RNA/Murine/B16.F10/ISMMS/B16.F10.0810/B16.F10.0810.127A/BAM/HISAT2/B16.F10.0810.127A_HISAT2.sorted.bam \
> --vaccine-peptide-length 25 \
> --mhc-predictor netmhccons \
> --mhc-alleles H2-Kb,H2-Db \
> --padding-around-mutation 5 \
> --output-html-report ~/Desktop/B16.F10.0810.127A.NetMHCcons.vaxrank.html
```

See: 
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/vaxrank", line 9, in <module>
    load_entry_point('vaxrank', 'console_scripts', 'vaxrank')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/johnfinnigan/Desktop/Utilities/Vaxrank/vaxrank/vaxrank/cli.py", line 19, in <module>
    from varcode.cli import variant_collection_from_args
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/varcode/__init__.py", line 17, in <module>
    from .maf import load_maf, load_maf_dataframe
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/varcode/maf.py", line 22, in <module>
    from .variant import Variant
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/varcode/variant.py", line 21, in <module>
    from pyensembl.biotypes import is_coding_biotype
ImportError: No module named biotypes
```

**Comment by iskandr** [comment]
LGTM 

Should fix https://github.com/hammerlab/vaxrank/issues/26

**Comment by iskandr** [comment]
Is this fixed by https://github.com/hammerlab/vaxrank/pull/27?

**Comment by JPFinnigan** [comment]
Nope.

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/vaxrank", line 9, in <module>
    load_entry_point('vaxrank', 'console_scripts', 'vaxrank')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/johnfinnigan/Desktop/Utilities/Vaxrank/vaxrank/vaxrank/cli.py", line 25, in <module>
    from isovar.cli.variant_sequences import make_variant_sequences_arg_parser
ImportError: No module named cli.variant_sequences
```

w/ invocation:
```
vaxrank --vcf ~/Desktop/WD/Results/WES/Murine/B16.F10/ISMMS/VCF/MuTect/B16.F10.0810_mutect.targets.pass.vcf --bam ~/Desktop/WD/Results/RNA/Murine/B16.F10/ISMMS/B16.F10.0810/B16.F10.0810.127A/BAM/HISAT2/B16.F10.0810.127A_HISAT2.sorted.bam --vaccine-peptide-length 25 --mhc-predictor netmhccons --mhc-alleles H2-Kb,H2-Db --padding-around-mutation 5 --output-html-report ~/Desktop/B16.F10.0810.127A.NetMHCcons.vaxrank.html
```

Isovar is in my PATH

**Comment by ihodes** [comment]
Mind sharing versions of isovar/other dependencies?

**Comment by julia326** [comment]
Also, worth it to run with the latest vaxrank just in case (a couple more small fixes went in today).

**Comment by ihodes** [comment]
(Resolved offline)
