### ISSUE TITLE
test_mutant_protein_sequence.py is flaky

### ISSUE THREAD

**Issue by julia326** [hammerlab/vaxrank#48]
Sometimes fails with:

```
vaxrank/vaxrank/core_logic.py:91: RuntimeWarning: invalid value encountered in double_scalars
  if vp.combined_score / max_score > 0.99
E..
======================================================================
ERROR: test.test_mutant_protein_sequence.test_mutant_amino_acids_in_mm10_chr9_82927102_refGT_altTG_pT441H
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/julia/Envs/vaxrank/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/julia/code/vaxrank/test/test_mutant_protein_sequence.py", line 91, in test_mutant_amino_acids_in_mm10_chr9_82927102_refGT_altTG_pT441H
    vaccine_peptide = vaccine_peptides[0]
IndexError: list index out of range
```

**Comment by iskandr** [comment]
That's really confusing! Looks like it might be related to floating point warning?

**Comment by iskandr** [comment]
@julia326 Just a reminder to myself that we need to understand this error (never observed on my machine, we should figure out when/how it happens).

**Comment by julia326** [comment]
@iskandr agreed - just happened again on Travis:

https://travis-ci.org/hammerlab/vaxrank/jobs/168180329

let's look at it tomorrow?
