### ISSUE TITLE
Running into shellinford issue

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/vaxrank#78]
On a clean `vaxrank` install:

```
vaxrank \
   --vcf test/data/b16.f10/b16.vcf \
   --bam test/data/b16.f10/b16.combined.bam \
   --vaccine-peptide-length 25 \
   --mhc-predictor netmhccons \
   --mhc-alleles 'HLA-A*30:01,HLA-A*32:01,HLA-B*07:02,HLA-B*18:01,HLA-C*07:02,HLA-C*07:01' \
   --padding-around-mutation 5 \
   --output-ascii-report vaccine-peptides-report.txt \
   --output-html-report vaccine-peptides-report.html \
   --output-pdf-report vaccine-peptides-report.pdf \
   --output-pickle-file report.pkl \
   --output-reviewed-by "John Doe,Jane Doe" \
   --output-final-review "All the Does" \
   --output-patient-id "Namey McName"
```

```
offset=5, mutant_amino_acid_end_offset=6, supporting_reference_transcripts=[Transcript(transcript_id=ENSMUST00000034787, name=Phip-003, gene_id=ENSMUSG00000032253, gene_name=Phip, biotype=protein_coding, location=9:82866159-82975516)], n_overlapping_reads=56, n_alt_reads=17, n_ref_reads=39, n_alt_reads_supporting_protein_sequence=2)
2016-11-03 22:04:59,881 - vaxrank.epitope_prediction - INFO - Loading FM index to /home/tavi/.cache/vaxrank/mus_musculus_85.fm
Traceback (most recent call last):
  File "/home/tavi/miniconda2/envs/vaxrank3/bin/vaxrank", line 11, in <module>
    load_entry_point('vaxrank', 'console_scripts', 'vaxrank')()
  File "/home/tavi/vaxrank/vaxrank/cli.py", line 255, in main
    template_data = load_template_data(args)
  File "/home/tavi/vaxrank/vaxrank/cli.py", line 190, in load_template_data
    min_epitope_score=args.min_epitope_score)
  File "/home/tavi/vaxrank/vaxrank/core_logic.py", line 184, in ranked_vaccine_peptides
    min_epitope_score=min_epitope_score)
  File "/home/tavi/vaxrank/vaxrank/core_logic.py", line 161, in generate_vaccine_peptides
    min_epitope_score=min_epitope_score)
  File "/home/tavi/vaxrank/vaxrank/core_logic.py", line 62, in vaccine_peptides_for_variant
    genome=variant.ensembl).values()
  File "/home/tavi/vaxrank/vaxrank/epitope_prediction.py", line 147, in predict_epitopes
    fm = load_reference_peptides_index(genome)
  File "/home/tavi/vaxrank/vaxrank/epitope_prediction.py", line 134, in load_reference_peptides_index
    path)
  File "/home/tavi/miniconda2/envs/vaxrank3/lib/python2.7/site-packages/shellinford/shellinford.py", line 444, in build
    self.fm.push_back(doc)
  File "/home/tavi/miniconda2/envs/vaxrank3/lib/python2.7/site-packages/shellinford/shellinford.py", line 292, in push_back
    return _shellinford.fm_index_push_back(self, *args)
TypeError: in method 'fm_index_push_back', argument 2 of type 'std::string const &'
```

**Comment by iskandr** [comment]
Still an issue?

**Comment by julia326** [comment]
I haven't been able to reproduce this, will need to look at Tavi's setup when he's back

**Comment by ihodes** [comment]
Can't repro this, assuming newest Shellingford fixed it.

**Comment by iskandr** [comment]
Having this same problem now.

**Comment by iskandr** [comment]
```
ERROR: test.test_shell_script.test_xlsx_report
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iskander/Library/Python/2.7/lib/python/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/iskander/code/vaxrank/test/test_shell_script.py", line 28, in test_xlsx_report
    run_shell_script(xlsx_args)
  File "/Users/iskander/code/vaxrank/vaxrank/cli.py", line 285, in main
    data = ranked_variant_list_with_metadata(args)
  File "/Users/iskander/code/vaxrank/vaxrank/cli.py", line 227, in ranked_variant_list_with_metadata
    variant_sequence_assembly=args.variant_sequence_assembly)
  File "/Users/iskander/code/vaxrank/vaxrank/core_logic.py", line 191, in ranked_vaccine_peptides
    min_epitope_score=min_epitope_score)
  File "/Users/iskander/code/vaxrank/vaxrank/core_logic.py", line 164, in generate_vaccine_peptides
    min_epitope_score=min_epitope_score)
  File "/Users/iskander/code/vaxrank/vaxrank/core_logic.py", line 61, in vaccine_peptides_for_variant
    genome=variant.ensembl).values()
  File "/Users/iskander/code/vaxrank/vaxrank/epitope_prediction.py", line 148, in predict_epitopes
    fm = load_reference_peptides_index(genome)
  File "/Users/iskander/code/vaxrank/vaxrank/epitope_prediction.py", line 135, in load_reference_peptides_index
    path)
  File "/usr/local/lib/python2.7/site-packages/shellinford-0.3.4-py2.7-macosx-10.10-x86_64.egg/shellinford/shellinford.py", line 444, in build
    self.fm.push_back(doc)
  File "/usr/local/lib/python2.7/site-packages/shellinford-0.3.4-py2.7-macosx-10.10-x86_64.egg/shellinford/shellinford.py", line 292, in push_back
    return _shellinford.fm_index_push_back(self, *args)
TypeError: in method 'fm_index_push_back', argument 2 of type 'std::string const &'
```

**Comment by ihodes** [comment]
Newest version of shellinford?

**Comment by julia326** [comment]
This is shellinford 0.3.4 - we haven't made any changes to this. I'm trying to reproduce on my machine now.

**Comment by iskandr** [comment]
Seems to only happen with Py2 on my machine while building the index (Py3 works fine)

**Comment by julia326** [comment]
Gut feeling that this is swig-related - I can't repro on my machine, but it's worth reinstalling swig (`brew install swig`) and `shellinford` after that to see if this is still happening.

**Comment by iskandr** [comment]
Vague suspicion that this might be unicode related, trying to `encode` as ASCII before `build`.
